### ISSUE TITLE
Request to Add a License to the Repository 

### ISSUE THREAD

**Issue by LeonideGra** [psalvaggio/local_laplacian_filters#1]
Hello,
Firstly thanks for creating this repo. Great project!
I'm interesting in using/contributing to it, but I noticed that there isn't a license specified for the project.
Would you consider adding a license to the repo? I would much appreciate it.
Thanks in advanced

**Comment by psalvaggio** [comment]
Done, sorry it took so long! I haven't touched this code in quite a long time, so I imagine there's a bit of work to be done to make it compatible with any recent versions of OpenCV.
